### ISSUE TITLE
What is needed to fix #11

### ISSUE THREAD

**Issue by szaimen** [nextcloud/vm#1116]
So here a short list what is probably needed to fix https://github.com/nextcloud/vm/issues/11 I will edit this list, if more comes to my mind

- [x]  1. edit download_static_script(), download_le_script(), run_main_script(), run_static_script(), run_app_script() in order to use the local scripts if existing at the correct place #1123
- [x] 2. edit all scripts in order to use the local lib.sh if existing at the correct place #1124
- [x] 3. provide an option to choose during the startup script if you want to use the local files or online files (Security vs bugfixes) and remove all local files (or at least most of them) when choosing security #1127
- [ ] 4. create a script that downloads the release file with the code from the github repository, compares it again the gpg key and extracts it to the right directory #1162
There are still ToDos missing. Advices: https://github.com/nextcloud/vm/pull/1126#issuecomment-593889476 downwards.
- [x] 5. edit all other scripts to use local files or inform the user if not possible; grep for curl: (nextcloud_install_prouduction, bitwarden, adminer, netdata, webmin, install_docker) #1125
- [ ] 6. sign and release the code

**Comment by szaimen** [comment]
@enoch85 please check out this list to get an idea what all PRs doing together
all are made so that they work without each other. But only of all are merged they will fix #11.

**Comment by szaimen** [comment]
I hope that all PRs have a fitting size so that they can get reviewed.

**Comment by szaimen** [comment]
Btw: until #1120 isn't merged AND used to make the VMs, everything will work as it currently is. Also if all other PRs are merged. 

So I would suggest merging #1120 at the last one. Then when using it, the true magic will happen ;)

**Comment by szaimen** [comment]
@enoch85 did you have time to look into this or the PRs a bit? :)

**Comment by enoch85** [comment]
Sorry, no time yet. :/

**Comment by enoch85** [comment]
OK, so I've merged all your PRs into the testing branch. 

Running the installer now. Don't have so much time to test, but at least I want to see how it looks.

**Comment by enoch85** [comment]
OK, so first test done. No errors, but the scripts doesn't work as intended. 

Please test for yourself and improve. 

One example is [here](https://github.com/nextcloud/vm/blob/testing/nextcloud-startup-script.sh#L273-L315), where you first ask if you want to run from Github or locally, then download scripts from Github either way.

Also the branch inside lib.sh wasn't set so files never downloaded as they should.

**Comment by szaimen** [comment]
Actually I am sure that already everything works.

The idea was that you use [this script](https://github.com/nextcloud/vm/pull/1126) for testing and for creating the VM. It downloads all files from the testing branch. if you then choose Security [here](https://github.com/nextcloud/vm/blob/testing/nextcloud-startup-script.sh#L273-L315) you will use the already downloaded local files from the testing branch. => perfect for testing.

BTW: Have you noticed, that I have changed `download_static_script` etc. in the lib file?
https://github.com/nextcloud/vm/blob/testing/lib.sh#L803-L863

And as I sayd before: The initial downloading etc could also get implemented into the install procudtion script...

**Comment by enoch85** [comment]
Since it's in a separate branch, feel free to merge and test as much a you want. :)

I didn't know about the new script actually, but that would explain why none of what you were mentioning worked. 

1. I didn't get all the scripts in the first setup
2. That resulted in that I never got presented with the option to choose "Security"
3. Scripts are downloaded from master even if "Security" would be chosen.

**Comment by szaimen** [comment]
> Since it's in a separate branch, feel free to merge and test as much a you want. :)
> 
> I didn't know about the new script actually, but that would explain why none of what you were mentioning worked.
> 
> 1. I didn't get all the scripts in the first setup
> 2. That resulted in that I never got presented with the option to choose "Security"
> 3. Scripts are downloaded from master even if "Security" would be chosen.

Then please use the script that I have mentioned first and afterwards choose the "Security" option during the startup script :)

**Comment by szaimen** [comment]
I think I have an idea how we could put the new script into the install_production script. Let me make a PR out of it...

**Comment by szaimen** [comment]
I've created #1162

**Comment by szaimen** [comment]
note to self:
The probably cleanest way of implementing point 2 is:
```
# shellcheck source=lib.sh
source /var/scripts/lib.sh &>/dev/null || . <(curl -sL https://raw.githubusercontent.com/nextcloud/vm/testing/lib.sh) &>/dev/null
```
