### ISSUE TITLE
TODO in the rewrite branch

### ISSUE THREAD

**Issue by enoch85** [nextcloud/vm#191]
**SHOULD WORK**
- [x] nextcloud-startup-script.sh
- [x] nextcloud_update.sh
- [X] adduser.sh
- [X] calendar.sh
- [X] change-ncadmin-profile.sh
- [X] change-root-profile.sh
- [x] change_mysql_pass.sh
- [x] collabora.sh
- [X] contacts.sh
- [X] history.sh
- [X] instruction.sh
- [X] ip.sh
- [X] ip2.sh
- [x] nextant.sh
- [X] nextcloud.sh
- [X] ntpdate.sh
- [x] passman.sh
- [X] recover_apps.py
- [x] redis-server-ubuntu16.sh
- [X] setup_secure_permissions_nextcloud.sh
- [x] spreedme.sh
- [X] temporary-fix.sh
- [X] test_connection.sh
- [X] trusted.sh
- [X] update-config.php
- [x] webmin.sh
- [x] phpmyadmin_install_ubuntu16.sh
- [x] security.sh
- [x] activate-ssl.sh
- [x] test-new-config.sh
- [x] lib.sh

**CLEAN UP LEFT**
- [ ] Adding spinner_loading for each time the lib.sh is imported (it takes a while and the marker just blinks) @morph027
- [x] Fix the LE issue in activate-ssl.sh (ATTEMPTS) @morph027 
- [x] Running the `run_*_script` make the output of the script that is run [disappear](https://github.com/nextcloud/vm/issues/191#issuecomment-292750219). We want to show the output. @morph027 
- [ ] Final tests
- [ ] Celebrate
- [X] Donate! :D

@morph027 Can you create PRs from here instead? Thanks!

**Comment by enoch85** [comment]
LE Error in activate-ssl.sh

Tested LE script and it generates a SSL cert, but keeps trying even if the cert is it succeeded. Can you have a look @morph027 ?

``` 
    # Check if $CERTFILES exists
    if [ -d "$CERTFILES" ]
    then
        # Generate DHparams chifer
        if [ ! -f "$DHPARAMS" ]
        then
            openssl dhparam -dsaparam -out "$DHPARAMS" 8192
        fi
        # Activate new config
        check_command bash "$SCRIPTS/test-new-config.sh" "$domain.conf"
    else
        printf "${ICyan}It seems like no certs were generated, we do %s more tries.${Color_Off}" "$((NR_OF_ATTEMPTS-ATTEMPT))"
        any_key "Press any key to continue..."
        ((ATTEMPT++))

    fi
done
```

**EDIT:** Let's Encrypt never ends: https://hastebin.com/anododotoz.php

**Comment by enoch85** [comment]
Show output instead of this in the installation  script:

```
System config value preview_libreoffice_path set to string /usr/bin/libreoffice

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.


WARNING: apt does not have a stable CLI interface. Use with caution in scripts.


WARNING: apt does not have a stable CLI interface. Use with caution in scripts.


WARNING: apt does not have a stable CLI interface. Use with caution in scripts.


WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Extracting templates from packages: 100%

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.


WARNING: apt does not have a stable CLI interface. Use with caution in scripts.


WARNING: apt does not have a stable CLI interface. Use with caution in scripts.


WARNING: apt does not have a stable CLI interface. Use with caution in scripts.


WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists... Done
```

Fix; maybe change back to -q2 on updates instead of -q4?

**Comment by enoch85** [comment]
@morph027 Can you please have a look at the LE issue? I'm on IRC if you want to discuss.

From IRC: "[19:02] enoch855: in case you want to do it properly: rewrite the body of your while loop into a function and call that function several times with your different options."

Also, how do we show output of the nested scripts?

**Comment by enoch85** [comment]
Also, the Apache method can be removed as it doesn't exist in that PPA we are using yet.

**Comment by enoch85** [comment]
Something like this maybe?

```
standalone() { 
echo certbot certonly --standalone; 
}

certonly() { 
echo ; 
}

webroot() {
echo certonly --webroot --webroot-path $NCPATH
}

methods=(standalone certonly webroot)

for f in "${methods[@]}"; do "$f"; done
```

**Comment by enoch85** [comment]
@morph027 I'm working on LE now, I'm close to fixing it, can you concentrate on the other stuff please?

**Comment by morph027** [comment]
Will do...Tomorrow should be some time left.

**Comment by enoch85** [comment]
I have done final tests now and everything works. As I said, I want to get this merged this weekend so I'll create an issue instead and assign it to you.

Merging to master now.
